const types = {
  UPDATE_CLICK_COORDINATES: "UPDATE_CLICK_COORDINATES",
  CLICK_CHARACTER: "CLICK_CHARACTER",
  SELECT_GAMEBOARD: "SELECT_GAMEBOARD",
  IDENTIFY_CHARACTER: "IDENTIFY_CHARACTER",
  PROVIDE_SELECTION_RESULT: "PROVIDE_SELECTION_RESULT",
};

export default types;
