const types = {
  UPDATE_CLICK_COORDINATES: "UPDATE_CLICK_COORDINATES",
  CLICK_CHARACTER: "CLICK_CHARACTER",
  SELECT_GAMEBOARD: "SELECT_GAMEBOARD",
  IDENTIFY_CHARACTER: "IDENTIFY_CHARACTER",
  PROVIDE_SELECTION_RESULT: "PROVIDE_SELECTION_RESULT",
  INCREMENT_SECONDS: "INCREMENT_SECONDS",
  INCREMENT_MINUTES: "INCREMENT_MINUTES",
  INCREMENT_HOURS: "INCREMENT_HOURS",
  SET_SECONDS: "SET_SECONDS",
  SET_MINUTES: "SET_MINUTES",
  PROVIDE_GAMEBOARD_DIMENSIONS: "PROVIDE_GAMEBOARD_DIMENSIONS",
};

export default types;
